packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@biomejs/biome': set this to true or false
  '@nestjs/core': set this to true or false
  bcrypt: set this to true or false
  unrs-resolver: set this to true or false

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@nestjs/core'
  - bcrypt
  - esbuild
  - 'unrs-resolver'
